version: "2.0"
services:
  mongo:
    image: mongo:4.2.0
    volumes:
      - ./volumes/mongo-data/:/data/db/:rw
    restart: always
    environment:
      TZ: Etc/UTC
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 7kB5RqW8wQ572nGOUmp5t4
  vcpub:
    build: ../vcpub
    volumes:
      - ../vcpub/conf.json:/vcpub/conf.json:ro
      - ../vcpub/src/:/vcpub/src/:ro
    restart: always
    environment:
      TZ: Etc/UTC
    command: npm run vcpub
  vkparser:
    build: ../vkparser
    volumes:
      - ../vkparser/build/:/vkparser/build/:ro
    restart: always
    environment:
      TZ: Etc/UTC
    command: npm run deploy
